import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--gnnlayers', type=int, default=3, help="Number of gnn layers")
parser.add_argument('--epochs', type=int, default=400, help='Number of epochs to train.')
parser.add_argument('--dims', type=int, default=[1000], help='Number of units in hidden layer 1.')
parser.add_argument('--lr', type=float, default=1e-3, help='Initial learning rate.')
parser.add_argument('--sigma', type=float, default=0.01, help='Sigma of gaussian distribution')
parser.add_argument('--dataset', type=str, default='citeseer', help='type of dataset.')
parser.add_argument('--cluster_num', type=int, default=7, help='type of dataset.')
parser.add_argument('--device', type=str, default='cuda:0', help='device')
parser.add_argument('--gama', type=float, default=0.5, help='Loss balance parameter')
parser.add_argument('--beta', type=float, default=0.5, help='Loss balance parameter')
parser.add_argument('--use_pseudo_label', type=bool, default=True)
parser.add_argument('--confidence_ratio', type=float, default=0.95)
parser.add_argument('--stage1_epochs', type=int, default=400)
parser.add_argument('--label_match_weight', type=float, default=0.5)
parser.add_argument('--global_layers', type=int, default=1)
args = parser.parse_args()
